version: '3.1'
services:
  reactjs-frontend:
    container_name: reactjs_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 82:3000

networks:
  default:
    driver: bridge
